workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Flutter test
        script: |
          flutter test
      - name: Build apk
        script: |
          flutter build apk --release \
            --build-number=$BUILD_NUMBER \
            --build-name=$PUBLISH_VERSION
      - name: Build app bundle
        script: |
          flutter build appbundle --release \
            --build-number=$BUILD_NUMBER \
            --build-name=$PUBLISH_VERSION
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
        submit_as_draft: true

